name: Check eslint
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['review', 'courses']

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  # pages: write
  # id-token: write

jobs:
  check-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./pnpm-lock.yaml
      
      - name: Install pnpm ğŸ”§
        shell: bash
        run: npm install -g pnpm

      - name: Install dependencies pnpm ğŸ”§
        shell: bash
        run: pnpm install --no-frozen-lockfile

      # - name: List files in directory ğŸ“‹ğŸ“
      #   shell: bash
      #   run: ls -R

      - name: Run eslint ğŸ§ª
        shell: bash
        run: pnpm run lint

      # - name: Build ğŸ”§
      #   shell: bash
      #   run:
      #     npm run build

      # - name: Setup Pages ğŸš€
      #   uses: actions/configure-pages@v3

      # - name: Upload artifact ğŸš€
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     # Upload dist repository
      #     path: './dist'

      # - name: Deploy to GitHub Pages ğŸš€
      #   id: deployment
      #   uses: actions/deploy-pages@v1